views:
- name: weather_map_html_map_view
  viewKind: html
  mimeType: text/html
  columns:
  - place
  - days
  - html_url
  rendererHint: html
- name: weather_map_forecast_data_view
  viewKind: json
  mimeType: application/json
  columns:
  - place
  - days
  - model
  rendererHint: json
